import React, { useRef, useState, useEffect } from 'react';

import Navbar from '../../navBar/Navbar';

import current_state_one from '/assets/img/icam_project_current_state_1.gif';
import Galaxy1 from '/assets/img/galactic_dreamscape_data/galaxy_1.jpg';
import Galaxy2 from '/assets/img/galactic_dreamscape_data/galaxy_2.jpg';
import Galaxy3 from '/assets/img/galactic_dreamscape_data/galaxy_3.jpg';
import Galaxy4 from '/assets/img/galactic_dreamscape_data/galaxy_4.jpg';
import Galaxy5 from '/assets/img/galactic_dreamscape_data/galaxy_5.jpg';
import Galaxy6 from '/assets/img/galactic_dreamscape_data/galaxy_6.jpg';
import Nebulae1 from '/assets/img/galactic_dreamscape_data/nebulae_1.jpg';
import Nebulae2 from '/assets/img/galactic_dreamscape_data/nebulae_2.jpg';
import Nebulae3 from '/assets/img/galactic_dreamscape_data/nebulae_3.jpg';
import Star1 from '/assets/img/galactic_dreamscape_data/star_1.jpg';
import task5_3_before from '/assets/img/galactic_dreamscape_data/task5-3_before.png';
import task5_3_add from '/assets/img/galactic_dreamscape_data/task5-3_add.jpg';
import task5_3progress_video from '/assets/img/galactic_dreamscape_data/task5.3-progress-video.mp4';

import relevantWork1 from '/assets/img/galactic_dreamscape_data/relevant_work_1.gif';
import relevantWork2 from '/assets/img/galactic_dreamscape_data/relevant_work_2.png';
import relevantWork3 from '/assets/img/galactic_dreamscape_data/relevant_work_3.jpg';

import finalImg1 from '/assets/img/galactic_dreamscape_data/final_img1.png';

const GalacticDreamscape = () => {

    useEffect(() => {
        document.title = "Galactic Dreamscape [2024] - Kaleo Cao";
    }, [])

    const images = [
        "https://personal-website-data.s3.us-east-2.amazonaws.com/galactic_dreamscape/img-1.png",
        "https://personal-website-data.s3.us-east-2.amazonaws.com/galactic_dreamscape/img-2.png",
        "https://personal-website-data.s3.us-east-2.amazonaws.com/galactic_dreamscape/img-3.png",
        "https://personal-website-data.s3.us-east-2.amazonaws.com/galactic_dreamscape/img-4.png",
        "https://personal-website-data.s3.us-east-2.amazonaws.com/galactic_dreamscape/img-5.png",
        "https://personal-website-data.s3.us-east-2.amazonaws.com/galactic_dreamscape/img-6.png",
        "https://personal-website-data.s3.us-east-2.amazonaws.com/galactic_dreamscape/img-7.png",
        "https://personal-website-data.s3.us-east-2.amazonaws.com/galactic_dreamscape/img-8.png",
        "https://personal-website-data.s3.us-east-2.amazonaws.com/galactic_dreamscape/img-9.png"
    ];

    const scrollRef = useRef(null);


    useEffect(() => {
        const scrollInterval = setInterval(() => {
            if (scrollRef.current) {
                scrollRef.current.scrollBy({ left: 150, behavior: 'smooth' });
            }
        }, 3000);

        return () => clearInterval(scrollInterval);
    }, []);


    return (
        <div>
            <Navbar />
            <main className='container'>

                <div className='container'>

                    <div className="col-12 col-md-10 col-lg-8">
                        <h2 className="row text-capitalizeer">Galactic Dreamscape [2024]</h2>
                    </div>

                    <div className="bordered-div py-2 my-4 fs-6 fw-light">
                        Technique: TouchDesigner, Sonic Pi, Leap Motion, Stable Diffusion, Prompting engineering, Projection mapping<br />
                        Note: This artwork generated by Stable Diffusion.
                    </div>

                </div>

                <div className='container pt-6'>

                    <div
                        ref={scrollRef}
                        className="d-flex overflow-auto"
                        style={{ whiteSpace: "nowrap" }}
                    >
                        {images.map((image, index) => (
                            <div key={index} style={{ flex: "0 0 33.33%", padding: "0 15px" }}>
                                <img
                                    src={image}
                                    className="img-fluid"
                                    alt={`Slide ${index}`}
                                    style={{ width: "100%" }}
                                />
                            </div>
                        ))}
                    </div>



                    <p className="pt-6">Space has always captured our imagination and inspired us to dream beyond Earth.
                        This fascination with the universe has sparked countless artistic creations,
                        each attempting to bring the wonders of the universe to us. For my senior project,
                        I developed a unique art installation that blends space exploration, human movement,
                        and cutting-edge technology to create an immersive experience.
                    </p>

                    <p className="pt-4">
                        The inspiration for this project comes from two main sources: NASA's space missions
                        and the graceful movements of astronauts in zero gravity. The NASA Hubble Space Telescope
                        and James Webb Space Telescope have provided breathtaking images of galaxies, nebulae, and
                        star clusters that offer a glimpse into the vast beauty of the universe. These cosmic vistas
                        serve as the backdrop for the installation, creating a realistic dreamscape that transports
                        viewers to the far reaches of space. At the same time, the project draws inspiration from the
                        fluid motions of astronauts as they float weightlessly in space. Their smooth, almost dance-like
                        movements stand in stark contrast to our everyday experiences on Earth. By incorporating these elements,
                        the installation aims to give viewers a taste of what it might feel like to move freely in a zero-gravity
                        environment.
                    </p>

                    <p className="pt-4">
                        The personal motivation for this project comes from a desire to push the boundaries of technology in art. Experimenting with Stable Diffusion, a powerful AI tool for generating images, allows for the exploration of new artistic possibilities. By applying data-driven approaches to the creative process, the project seeks to blend the precision of technology with the emotional impact of art.
                    </p>

                    <p className="pt-4">
                        This project also reflects my fascination with space and the cosmos. It's an opportunity for me to delve deeper into these themes, using art as a medium to express the awe and wonder that the universe inspires. Through this installation, I hope to create an immersive experience that not only captivates viewers but also educates them about the realities of dreamscape travel and astronaut movement.
                    </p>

                    <p className="pt-4">
                        This artwork draws on several influential work in the field of technology-driven art.
                        Memo Akten's work "Learning to see: We are made of star dust" demonstrates how artificial intelligence
                        and machine learning can transform live video in real time to create visually impressive effects. This
                        technique of using neural networks to process images in real time inspired the project's approach to creating
                        dynamic, resonsive visuals. Second, teamLab's "Universe of Water Particles under Satellite's Gravity" offers
                        insights into how 3D modeling and particle systems can be used to create interactive installations. By simulating
                        the effects of gravity on water particles, teamLab has created a work that blends traditional Japanese
                        aesthetics with modern technology. This fusion of old and new serves as an example of how space-themed art
                        can bridge different cultural and technological spheres. Third, Tomas Saraceno's "The politics of solar rhythms: Cosmic Levitation"
                        provides a unique perspective on how sound can be used to manipulate physical objects, mimicking the
                        formation of planets from cosmic dust. This integration of scientific principles into art has
                        influenced the current project's aim to make abstract space concepts more tangible and relatable to viewers.
                    </p>

                </div>

                <section id="timeline" className="timeline_area section_padding_130 mt-6">
                    <div className="container">

                        <div className="row">
                            <div className="col-12">
                                {/* Timeline Area */}
                                <div className="apland-timeline-area">
                                    {/* Week 1 */}
                                    <div className="single-timeline-area">
                                        <div className="timeline-date wow fadeInLeft" data-wow-delay="0.1s" style={{ visibility: 'visible', animationDelay: '0.1s', animationName: 'fadeInLeft' }}>
                                            <p>Week 1</p>
                                        </div>
                                        <div className="row">
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 1.1</h5>
                                                        <p>Finalize project proposal</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.5s" style={{ visibility: 'visible', animationDelay: '0.5s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 1.2</h5>
                                                        <p>Install TouchDesigner, Stable Diffusion, and other necessary software</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.7s" style={{ visibility: 'visible', animationDelay: '0.7s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 1.3</h5>
                                                        <p>Set up development environment</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Week 2 */}
                                    <div className="single-timeline-area">
                                        <div className="timeline-date wow fadeInLeft" data-wow-delay="0.1s" style={{ visibility: 'visible', animationDelay: '0.1s', animationName: 'fadeInLeft' }}>
                                            <p>Week 2</p>
                                        </div>
                                        <div className="row">
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 2.1</h5>
                                                        <p>Learn TouchDesigner basic (tutorial, practice projects)</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.5s" style={{ visibility: 'visible', animationDelay: '0.5s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 2.2</h5>
                                                        <p>Find and download relevant NASA dataset</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.5s" style={{ visibility: 'visible', animationDelay: '0.5s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 2.3</h5>
                                                        <p>Refine and detail the project timeline</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Week 3 */}
                                    <div className="single-timeline-area">
                                        <div className="timeline-date wow fadeInLeft" data-wow-delay="0.1s" style={{ visibility: 'visible', animationDelay: '0.1s', animationName: 'fadeInLeft' }}>
                                            <p>Week 3</p>
                                        </div>
                                        <div className="row">
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 3.1</h5>
                                                        <p>Continue learning advanced TouchDesigner techniques (particle effects and fluid simulation)</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div
                                                className="col-12 col-md-6 col-lg-4"
                                                data-bs-toggle="modal"
                                                data-bs-target="#take3.2Modal"
                                            >
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.5s" style={{ visibility: 'visible', animationDelay: '0.5s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 3.2</h5>
                                                        <p>Clean and preprocessing NASA dataset for integration</p>
                                                    </div>
                                                </div>
                                            </div>



                                            <div
                                                className="col-12 col-md-6 col-lg-4"
                                                data-bs-toggle="modal"
                                                data-bs-target="#task3.3Modal"
                                            >
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.7s" style={{ visibility: 'visible', animationDelay: '0.7s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 3.3</h5>
                                                        <p>Research three relevant interactive art installation for inspiration</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Week 4 */}
                                    <div className="single-timeline-area">
                                        <div className="timeline-date wow fadeInLeft" data-wow-delay="0.1s" style={{ visibility: 'visible', animationDelay: '0.1s', animationName: 'fadeInLeft' }}>
                                            <p>Week 4</p>
                                        </div>
                                        <div className="row">
                                            <div
                                                className="col-12 col-md-6 col-lg-4"
                                                data-bs-toggle="modal"
                                                data-bs-target="#task4.1Modal"
                                            >
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 4.1</h5>
                                                        <p>Begin drafting the project framework in TouchDesigner</p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 4.2</h5>
                                                        <p>Start building the project website to document progress</p>
                                                    </div>
                                                </div>
                                            </div>


                                        </div>
                                    </div>

                                    {/* Week 5 */}
                                    <div className="single-timeline-area">
                                        <div className="timeline-date wow fadeInLeft" data-wow-delay="0.1s" style={{ visibility: 'visible', animationDelay: '0.1s', animationName: 'fadeInLeft' }}>
                                            <p>Week 5</p>
                                        </div>
                                        <div className="row">
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 5.1</h5>
                                                        <p>Present project progress</p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 5.2</h5>
                                                        <p>Update the project proposal</p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div
                                                className="col-12 col-md-6 col-lg-4"
                                                data-bs-toggle="modal"
                                                data-bs-target="#task5.3Modal"
                                            >
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 5.3</h5>
                                                        <p>Experiment with initial visual element using NASA data</p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div
                                                className="col-12 col-md-6 col-lg-4"
                                                data-bs-toggle="modal"
                                                data-bs-target="#task5.4Modal"
                                            >
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 5.4</h5>
                                                        <p>Develop the final workflow design in TouchDesigner, detailing how each component connects and interacts.</p>
                                                    </div>
                                                </div>
                                            </div>


                                        </div>
                                    </div>

                                    {/* Week 6 */}
                                    <div className="single-timeline-area">
                                        <div className="timeline-date wow fadeInLeft" data-wow-delay="0.1s" style={{ visibility: 'visible', animationDelay: '0.1s', animationName: 'fadeInLeft' }}>
                                            <p>Week 6</p>
                                        </div>
                                        <div className="row">
                                            <div
                                                className="col-12 col-md-6 col-lg-4"
                                                data-bs-toggle="modal"
                                                data-bs-target="#task6.1Modal"
                                            >
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 6.1</h5>
                                                        <p>Fill out Exhibition List with my project information</p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 6.2</h5>
                                                        <p>Implement Leap Motion integration for tracking human movement</p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 6.3</h5>
                                                        <p>Develop basic interactive component (particle effects reacting to movement)</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Week 7 & 8*/}
                                    <div className="single-timeline-area">
                                        <div className="timeline-date wow fadeInLeft" data-wow-delay="0.1s" style={{ visibility: 'visible', animationDelay: '0.1s', animationName: 'fadeInLeft' }}>
                                            <p>Week 7 & 8</p>
                                        </div>
                                        <div className="row">
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 7-8.1</h5>
                                                        <p>Start integrating cleaned NASA datasets into the project</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 7-8.2</h5>
                                                        <p>Refine interactive elements based on testing and feedback</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 7-8.3</h5>
                                                        <p>Continue integrating and testing NASA data within the visual elements</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    {/* Week 9 */}
                                    <div className="single-timeline-area">
                                        <div className="timeline-date wow fadeInLeft" data-wow-delay="0.1s" style={{ visibility: 'visible', animationDelay: '0.1s', animationName: 'fadeInLeft' }}>
                                            <p>Week 9</p>
                                        </div>
                                        <div className="row">
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 9.1</h5>
                                                        <p>Finalize all visual and interactive elements</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>

                                                    <div className="timeline-text">
                                                        <h5>Task 9.2</h5>
                                                        <p>Prepare final presentation materials</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Week 10 */}
                                    <div className="single-timeline-area">
                                        <div className="timeline-date wow fadeInLeft" data-wow-delay="0.1s" style={{ visibility: 'visible', animationDelay: '0.1s', animationName: 'fadeInLeft' }}>
                                            <p>🎉 Week 10</p>
                                        </div>
                                        <div className="row">
                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 10.1</h5>
                                                        <p>Complete the project website with documentation</p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 10.2</h5>
                                                        <p>Setup the installation </p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="col-12 col-md-6 col-lg-4">
                                                <div className="single-timeline-content d-flex wow fadeInLeft" data-wow-delay="0.3s" style={{ visibility: 'visible', animationDelay: '0.3s', animationName: 'fadeInLeft' }}>
                                                    <div className="timeline-text">
                                                        <h5>Task 10.3</h5>
                                                        <p>Deliver final presentation</p>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </section>



                {/* <div className="container pb-6">
                    <audio controls>
                        <source src="/assets/img/galactic_dreamscape_data/sample.mp3" type="audio/mp3" />
                        Your browser does not support the audio element.
                    </audio>


                    <div style={{ padding: '55% 0 0 0', position: 'relative' }}>
                        <iframe
                            src="https://player.vimeo.com/video/1000504206?badge=0&autopause=0&player_id=0&app_id=58479"
                            
                            allow="autoplay; fullscreen; picture-in-picture; clipboard-write"
                            style={{ position: 'absolute', top: '0', left: '0', width: '100%', height: '100%' }}
                            title="Particle System Progress"
                        ></iframe>
                    </div>
                    <script src="https://player.vimeo.com/api/player.js"></script>
                </div> */}







                <div className="container mt-6 mb-6">

                    <p className="pt-4 pb-6">
                        The driving force behind this work is the desire to change people's perception of space and the
                        possibility of living beyond Earth. By creating an immersive experience, the installation aims
                        to create a deeper emotional and intellectual connection between the viewer and the concept of
                        space habitation. This is to make the seemingly distant and abstract idea of living in space more
                        real and feasible. In addition, the project highlights the potential of art and technology to
                        shape our understanding and approach to space exploration. By combining dynamic visuals and interactive
                        elements, the installation serves as a bridge between scientific knowledge and public engagement.
                    </p>

                    <h3 className="text-capitalize">Galactic Dreamscape Gallery Walkthrough</h3>
                    <div style={{ position: 'relative', width: '100%', height: 0, paddingBottom: '45%' }}>
                        <iframe
                            src="https://player.vimeo.com/video/1007852050?title=0&byline=0&portrait=0&badge=0&autopause=0&player_id=0&app_id=58479"
                            frameBorder="0"
                            allow="autoplay; fullscreen; picture-in-picture; clipboard-write"
                            style={{ position: 'absolute', top: '0', left: '0', width: '100%', height: '100%' }}
                            title="Galactic Dreamscape Gallery Walkthrough"
                        ></iframe>
                    </div>

                    {/* Art Installation Design */}
                    <div className='mb-4'>


                        <h5 className="text-capitalize">Space Fantasy Environment</h5>
                        <ul className="list-bullet">
                            <li>
                                <strong>Visual:</strong> Using StreamDiffusionTD, the installation will generate real-time img2img transformations to create evolving space landscapes. Participants will find themselves surrounded by swirling nebulas, star fields, and alien terrains that react their presence.
                            </li>
                            <li>
                                <strong>Human Body Movement:</strong> Participants’ movements will be tracked using Leap Motion sensors, translating their gestures and poses into visual data. This data will influence the particle simulations and fluid dynamics, creating a responsive and interactive visual experience.
                            </li>

                        </ul>

                        <h5 className="text-capitalize">Interactive Components</h5>
                        <ul className="list-bullet">
                            <li>
                                <strong>Particle Effects:</strong> The installation will feature interactive particle system that react to human movement. As participants move, particles will follow their gestures, creating trails and shapes that mimic cosmic dust, energy flows, and nebula formations.
                            </li>

                        </ul>
                    </div>
                </div>

                {/* Task 3.2 Modal */}
                <div
                    className="modal fade"
                    id="take3.2Modal"
                    tabIndex="-1"
                    aria-labelledby="take3.2ModalLabel"
                    aria-hidden="true"
                >
                    <div className="modal-dialog modal-dialog-centered modal-lg">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title" id="take3.2ModalLabel">Task 3.2 Progress</h5>
                                <button
                                    type="button"
                                    className="btn-close"
                                    data-bs-dismiss="modal"
                                    aria-label="Close"
                                ></button>
                            </div>
                            <div className="modal-body">
                                <div id="carouselExampleInterval" className="carousel slide" data-bs-ride="carousel">
                                    <div className="carousel-inner" style={{ borderRadius: '10px' }}>
                                        <div className="carousel-item active" data-bs-interval="10000">
                                            <img src={Galaxy1} className="d-block w-100 custom-img" alt="..." />
                                        </div>
                                        <div className="carousel-item" data-bs-interval="2000">
                                            <img src={Galaxy2} className="d-block w-100 custom-img" alt="..." />
                                        </div>
                                        <div className="carousel-item">
                                            <img src={Nebulae3} className="d-block w-100 custom-img" alt="..." />
                                        </div>
                                        <div className="carousel-item">
                                            <img src={Galaxy3} className="d-block w-100 custom-img" alt="..." />
                                        </div>
                                        <div className="carousel-item">
                                            <img src={Nebulae2} className="d-block w-100 custom-img" alt="..." />
                                        </div>
                                        <div className="carousel-item">
                                            <img src={Galaxy4} className="d-block w-100 custom-img" alt="..." />
                                        </div>
                                        <div className="carousel-item">
                                            <img src={Galaxy5} className="d-block w-100 custom-img" alt="..." />
                                        </div>
                                        <div className="carousel-item">
                                            <img src={Galaxy6} className="d-block w-100 custom-img" alt="..." />
                                        </div>
                                        <div className="carousel-item">
                                            <img src={Nebulae1} className="d-block w-100 custom-img" alt="..." />
                                        </div>
                                        <div className="carousel-item">
                                            <img src={Star1} className="d-block w-100 custom-img" alt="..." />
                                        </div>
                                    </div>
                                    <button className="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
                                        <span className="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span className="visually-hidden">Previous</span>
                                    </button>
                                    <button className="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
                                        <span className="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span className="visually-hidden">Next</span>
                                    </button>
                                </div>
                                <p className="py-5">I selected 120 images from three categories—Galaxies, Nebulae, and Star Clusters—on the NASA website. My selection criteria were based on color, composition, and an additional factor that enhances the visual appeal and scientific significance of each image.</p>

                            </div>

                        </div>
                    </div>
                </div>

                {/* Task 3.3 Modal */}
                <div
                    className="modal fade"
                    id="task3.3Modal"
                    tabIndex="-1"
                    aria-labelledby="task3.3ModalLabel"
                    aria-hidden="true"
                >
                    <div className="modal-dialog modal-dialog-centered modal-lg">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title" id="task3.3ModalLabel">Task 3.3 Progress: Research Three Relevant Works</h5>
                                <button
                                    type="button"
                                    className="btn-close"
                                    data-bs-dismiss="modal"
                                    aria-label="Close"
                                ></button>
                            </div>
                            <div className="modal-body">


                                <div class="row mb-5">
                                    <div class="col-sm-8">
                                        <p><strong>Title: </strong>Learning to see: We are made of star dust</p>
                                        <p><strong>Artist: </strong>Memo Akten</p>
                                        <p><strong>Year: </strong>2017</p>
                                        <p><strong>Technique: </strong>custom software, AI, machine learning, deep learning, generative adversarial networks</p>
                                        <p><strong>Link: </strong><a href='https://www.memo.tv/works/we-are-made-of-star-dust/' target='_blank' style={{ color: 'black', textDecoration: 'underline' }}>https://www.memo.tv/works/we-are-made-of-star-dust/</a></p>
                                        <p><strong>Paper: </strong><a href='https://research.gold.ac.uk/id/eprint/30191/1/COM_thesis_AktenM_2021.pdf' target='_blank' style={{ color: 'black', textDecoration: 'underline' }}>https://research.gold.ac.uk/id/eprint/30191/1/COM_thesis_AktenM_2021.pdf</a></p>

                                        <p><strong>Takeaways:</strong>
                                            <ul className="list-bullet">
                                                <li>
                                                    The system takes live video and change how it looks while reconstructing image in composition and overall shape
                                                </li>
                                                <li>
                                                    Train a number of models on large datasets of images &#8594; load to real-time inference software &#8594; user can manipulate a number of human-understandable parameters in real-time via a GUI
                                                </li>
                                                <li>
                                                    Neural network architecture based on pix2pix image-to-image translation
                                                </li>
                                                <li>
                                                    <strong>Data augmentation</strong>: images processing in different ways (like flipping or making them brighter) to help the computer learn better
                                                </li>
                                            </ul>
                                        </p>


                                    </div>
                                    <div class="col-sm-4">
                                        <img src={relevantWork1} class="ml-3" alt="..." />
                                    </div>
                                </div>

                                <div className="row mb-5">

                                    <div class="col-sm-8">
                                        <p><strong>Title: </strong>Universe of Water Particles under Satellite’s Gravity</p>
                                        <p><strong>Art Collective: </strong>teamLab</p>
                                        <p><strong>Year: </strong>2014</p>
                                        <p><strong>Link: </strong><a href='https://www.teamlab.art/w/satellites-gravity/space-art/' target='_blank' style={{ color: 'black', textDecoration: 'underline' }}>https://www.teamlab.art/w/satellites-gravity/space-art/</a></p>

                                        <p><strong>Takeaways:</strong>
                                            <ul className="list-bullet">
                                                <li>
                                                    A computer model of a real satellite was made in 3D
                                                </li>
                                                <li>
                                                    The model has fake gravity that pulls water towards it
                                                </li>
                                                <li>
                                                    Tiny water drops were created to act like real water
                                                </li>
                                                <li>
                                                    Some water drops were turned into lines to look like a waterfall
                                                </li>
                                                <li>
                                                    The artwork mixes old Japanese ideas with new computer tech
                                                </li>
                                            </ul>
                                        </p>
                                    </div>

                                    <div class="col-sm-3">
                                        <img src={relevantWork2} class="ml-3" alt="..." />
                                    </div>
                                </div>

                                <div className="row mb-5">

                                    <div class="col-sm-8">
                                        <p><strong>Title: </strong>The politics of solar rhythms: Cosmic Levitation</p>
                                        <p><strong>Artist: </strong>Tomas Saraceno</p>
                                        <p><strong>Year: </strong>2018</p>
                                        <p><strong>Link: </strong><a href='https://studiotomassaraceno.org/the-politics-of-solar-rhythms-cosmic-levitation/' target='_blank' style={{ color: 'black', textDecoration: 'underline' }}>https://studiotomassaraceno.org/the-politics-of-solar-rhythms-cosmic-levitation/</a></p>

                                        <p><strong>Takeaways:</strong>
                                            <ul className="list-bullet">
                                                <li>
                                                    Using sound waves to make tiny space dust float in the air
                                                </li>
                                                <li>
                                                    This experiment helps understand how planets might form from space dust.
                                                </li>
                                                <li>
                                                    The experiment connects ideas about space, sound, and human history
                                                </li>
                                                <li>
                                                    The artwork uses live temperature differences to make sounds
                                                </li>
                                                <li>
                                                    The project mixes science experiments with art and big ideas about the universe
                                                </li>
                                            </ul>
                                        </p>
                                    </div>

                                    <div class="col-sm-4">
                                        <img src={relevantWork3} class="ml-3" alt="..." />
                                    </div>
                                </div>

                                <h3>Reflection</h3>

                                <p className='mb-2'>
                                    &emsp; Memo Akten, teamLab, and Tomas Saraceno inspire me with their innovative use of technology and interactivity in their art. Memo’s work with machine learning and deep learning algorithms to reconstruct images aligns closely with my aesthetic goals, while teamLab’s use of simulated gravity to create waterfalls resonates with my desire to incorporate similar effects in my project proposal. Tomas Saraceno’s work make me consider narrowing down my research question or developing a more specific focus for the art installation. His use of interdisciplinary elements has also encouraged me to think about incorporating sound into my project, if time allows. This could add another layer of depth to the experience, enhancing the overall impact of the installation
                                </p>

                                <p>
                                    &emsp; I believe my project is feasible because TouchDesigner supports complex visual effects and AI integrations. I also learned a basic understanding of TouchDesigner’s components and operators. However, I need to review some of these elements again to better understanding their connection logic. I discovered these artists through different channels. I follow teamLab’s Instagram account. As for Tomas Saraceno, I learned about his work from VIS 159 class presentation last quarter, which was part of a list curated by Memo Akten. My project will use different visual element to show zero gravity. I have not decided yet. My project also uses images capture from telescope to make more futurism, unlike memo's work using nature to generate space.
                                </p>



                            </div>

                        </div>
                    </div>
                </div>

                {/* Task 4.1 Modal */}
                <div
                    className="modal fade"
                    id="task4.1Modal"
                    tabIndex="-1"
                    aria-labelledby="task4.1ModalLabel"
                    aria-hidden="true"
                >
                    <div className="modal-dialog modal-dialog-centered modal-lg">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title" id="task4.1ModalLabel">Task 4.1 Progress: Fluid Simulation</h5>
                                <button
                                    type="button"
                                    className="btn-close"
                                    data-bs-dismiss="modal"
                                    aria-label="Close"
                                ></button>
                            </div>
                            <div className="modal-body">
                                <div>
                                    <img src={current_state_one} style={{ borderRadius: '15px' }} alt="description" />
                                </div>

                                <p className='py-5'>
                                    Fluid Simulation controlled by mouse, with parameters including velocity, gradient color value, pressure, and brush stroke.
                                </p>

                            </div>

                        </div>
                    </div>
                </div>

                {/* Task 5.3 Modal */}
                <div
                    className="modal fade"
                    id="task5.3Modal"
                    tabIndex="-1"
                    aria-labelledby="task5.3ModalLabel"
                    aria-hidden="true"
                >
                    <div className="modal-dialog modal-dialog-centered modal-lg">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title" id="task5.3ModalLabel">Task 5.3 Progress</h5>
                                <button
                                    type="button"
                                    className="btn-close"
                                    data-bs-dismiss="modal"
                                    aria-label="Close"
                                ></button>
                            </div>
                            <div className="modal-body">

                                <h4>Before</h4>
                                <div className='pb-4'>
                                    <img src={task5_3_before} style={{ width: '50%', height: '40%', borderRadius: '15px' }} alt="description" />
                                </div>


                                <h4>After</h4>
                                <img src={task5_3_add} className='pb-5' style={{ width: '50%', height: '50%' }} alt="description" />

                                <div className="ratio ratio-16x9">

                                    <video className="w-100" controls autoplay muted>
                                        <source src={task5_3progress_video} type="video/mp4" />
                                        Your browser does not support the video tag.
                                    </video>
                                </div>

                                <p className='py-5'>

                                </p>

                            </div>

                        </div>
                    </div>
                </div>

                {/* Task 5.4 Modal */}
                <div
                    className="modal fade"
                    id="task5.4Modal"
                    tabIndex="-1"
                    aria-labelledby="task5.4ModalLabel"
                    aria-hidden="true"
                >
                    <div className="modal-dialog modal-dialog-centered modal-xl">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title" id="task5.4ModalLabel">Task 5.4 Progress: System Design</h5>
                                <button
                                    type="button"
                                    className="btn-close"
                                    data-bs-dismiss="modal"
                                    aria-label="Close"
                                ></button>
                            </div>
                            <div className="modal-body" style={{ height: '80vh' }}>
                                <iframe
                                    style={{
                                        border: '1px solid rgba(0, 0, 0, 0.1)',
                                        width: '100%',
                                        height: '100%',
                                    }}
                                    src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fdesign%2FTEW2c0iBpmELL66caGyXdq%2FICAM-Senior-Project-Workflow%3Fnode-id%3D0-1%26t%3D4FaHa90C9GyAb134-1"
                                    allowFullScreen
                                ></iframe>
                            </div>


                        </div>
                    </div>
                </div>

                {/* Task 6.1 Modal */}
                <div
                    className="modal fade"
                    id="task6.1Modal"
                    tabIndex="-1"
                    aria-labelledby="task6.1ModalLabel"
                    aria-hidden="true"
                >
                    <div className="modal-dialog modal-dialog-centered modal-lg">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title" id="task6.1ModalLabel">Task 6.1 Progress</h5>
                                <button
                                    type="button"
                                    className="btn-close"
                                    data-bs-dismiss="modal"
                                    aria-label="Close"
                                ></button>
                            </div>
                            <div className="modal-body">
                                <ul className="list-bullet">
                                    <li>
                                        <strong>Title:</strong> Galactic Dreamscape
                                    </li>
                                    <li>
                                        <strong>Format:</strong> Digital media, projection, and interactive technology
                                    </li>
                                    <li>
                                        <strong>Website:</strong> <a href="https://www.kaleo-cao.com/artworks/GalacticDreamscape" target='_blank' style={{ color: 'black', textDecoration: 'underline' }}> https://www.kaleo-cao.com/artworks/GalacticDreamscape</a>
                                    </li>
                                    <li>
                                        <strong>Equipment Specifications: </strong> Computer installed the TouchDesigner, Kinect, and Projector [Resolution: 1024x768; Throw Distance: 5.3' - 34.3']
                                    </li>
                                    <li>
                                        <strong>Installation Specifications: </strong> <br></br>
                                        <ul className="list-bullet">
                                            <li><strong>Gallery Space</strong>: Minimum 10x10 feet, depending on the projection size and viewer interaction area</li>
                                        </ul>

                                        <p className='font-weight-bold'>Setup</p>
                                        <ul className="list-bullet">
                                            <li><strong>Kinect</strong>: Place the Kinect at a height that captures the entire interaction area.</li>
                                            <li><strong>Projector</strong>: Mount the projector securely and alig it with the projector surface.</li>
                                            <li><strong>Computer</strong>: Place the computer in flat area near the projector and Kinect.</li>
                                        </ul>

                                    </li>
                                    <li>
                                        <strong>PR Image (150x150) & Doc image (150/x150):</strong>
                                    </li>
                                </ul>

                            </div>

                        </div>
                    </div>
                </div>



            </main >
        </div >
    )
}

export default GalacticDreamscape